
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASIG BOOL CHAR COLON COMMA DIVIDE DOT DOUBLE_COLON DOUBLE_QUOTATION_MARK ELSE EQ EXCLAMATION F32 F64 FALSE FLOAT FN FOR FROM GEQ I16 I32 I64 I8 IDENTIFIER IF IMPL IN INTD INTEGER IO ISIZE LCORCH LEFTARROW LEQ LET LLLAVE LPAREN MAIN MATCH MINUS MOD MUT NEQ NOT OR PLUS PRINTLN QUOTATION_MARK RAND RCORCH READLINE REFERENCE RETURN RIGHTARROW RLLAVE RPAREN SELF SEMICOLON STD STDIN STR STRING STRUCT TIMES TRUE U128 U16 U32 U64 U8 USIZE WHILEprograma : sentencias SEMICOLON\n              | sentencias programa\n  asignacion : LET IDENTIFIER EQ valor\n  valor : INTEGER \n          | FLOAT \n          | IDENTIFIER\n  \n  \n  sentencias : asignacion \n              | impresion\n              | funcion\n              | ingreso_datos\n              | arreglos\n\n  \n  impresion : PRINTLN LPAREN valor RPAREN\n  \n  \n  funcion : FN IDENTIFIER LPAREN RPAREN LLLAVE programa RLLAVE\n  \n  \n  ingreso_datos : STD DOUBLE_COLON IO DOUBLE_COLON DOT STDIN LPAREN RPAREN DOT READLINE LPAREN REFERENCE MUT IDENTIFIER RPAREN\n\n  \n  arreglos : LCORCH valor RCORCH\n\n  '
    
_lr_action_items = {'LET':([0,2,3,4,5,6,7,20,21,22,27,28,29,32,36,45,],[8,8,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,8,-13,-14,]),'PRINTLN':([0,2,3,4,5,6,7,20,21,22,27,28,29,32,36,45,],[9,9,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,9,-13,-14,]),'FN':([0,2,3,4,5,6,7,20,21,22,27,28,29,32,36,45,],[10,10,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,10,-13,-14,]),'STD':([0,2,3,4,5,6,7,20,21,22,27,28,29,32,36,45,],[11,11,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,11,-13,-14,]),'LCORCH':([0,2,3,4,5,6,7,20,21,22,27,28,29,32,36,45,],[12,12,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,12,-13,-14,]),'$end':([1,13,14,],[0,-1,-2,]),'SEMICOLON':([2,3,4,5,6,7,20,21,22,27,28,29,36,45,],[13,-7,-8,-9,-10,-11,-4,-5,-6,-15,-3,-12,-13,-14,]),'IDENTIFIER':([8,10,12,16,23,43,],[15,17,22,22,22,44,]),'LPAREN':([9,17,35,40,],[16,25,37,41,]),'DOUBLE_COLON':([11,26,],[18,31,]),'INTEGER':([12,16,23,],[20,20,20,]),'FLOAT':([12,16,23,],[21,21,21,]),'RLLAVE':([13,14,34,],[-1,-2,36,]),'EQ':([15,],[23,]),'IO':([18,],[26,]),'RCORCH':([19,20,21,22,],[27,-4,-5,-6,]),'RPAREN':([20,21,22,24,25,37,44,],[-4,-5,-6,29,30,38,45,]),'LLLAVE':([30,],[32,]),'DOT':([31,38,],[33,39,]),'STDIN':([33,],[35,]),'READLINE':([39,],[40,]),'REFERENCE':([41,],[42,]),'MUT':([42,],[43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,2,32,],[1,14,34,]),'sentencias':([0,2,32,],[2,2,2,]),'asignacion':([0,2,32,],[3,3,3,]),'impresion':([0,2,32,],[4,4,4,]),'funcion':([0,2,32,],[5,5,5,]),'ingreso_datos':([0,2,32,],[6,6,6,]),'arreglos':([0,2,32,],[7,7,7,]),'valor':([12,16,23,],[19,24,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencias SEMICOLON','programa',2,'p_programa','sintax.py',5),
  ('programa -> sentencias programa','programa',2,'p_programa','sintax.py',6),
  ('asignacion -> LET IDENTIFIER EQ valor','asignacion',4,'p_asignacion','sintax.py',10),
  ('valor -> INTEGER','valor',1,'p_valor','sintax.py',14),
  ('valor -> FLOAT','valor',1,'p_valor','sintax.py',15),
  ('valor -> IDENTIFIER','valor',1,'p_valor','sintax.py',16),
  ('sentencias -> asignacion','sentencias',1,'p_sentencias','sintax.py',21),
  ('sentencias -> impresion','sentencias',1,'p_sentencias','sintax.py',22),
  ('sentencias -> funcion','sentencias',1,'p_sentencias','sintax.py',23),
  ('sentencias -> ingreso_datos','sentencias',1,'p_sentencias','sintax.py',24),
  ('sentencias -> arreglos','sentencias',1,'p_sentencias','sintax.py',25),
  ('impresion -> PRINTLN LPAREN valor RPAREN','impresion',4,'p_impresion','sintax.py',30),
  ('funcion -> FN IDENTIFIER LPAREN RPAREN LLLAVE programa RLLAVE','funcion',7,'p_funcion','sintax.py',36),
  ('ingreso_datos -> STD DOUBLE_COLON IO DOUBLE_COLON DOT STDIN LPAREN RPAREN DOT READLINE LPAREN REFERENCE MUT IDENTIFIER RPAREN','ingreso_datos',15,'p_ingreso','sintax.py',42),
  ('arreglos -> LCORCH valor RCORCH','arreglos',3,'p_arreglos','sintax.py',48),
]
