#@author Fausto-Briones
reserved = {
  'if': 'IF',
  'else': 'ELSE',
  'while': 'WHILE',
  'for': 'FOR',
  'in': 'IN',
  'fn': 'FN',
  'let': 'LET',
  'true': 'TRUE',
  'false': 'FALSE',
  'and': 'AND',
  'or': 'OR',
  'match':"MATCH",
  'impl':'IMPL',
  'Self':'SELF',
  'str': 'STR',
  'struct':'STRUCT',
  'String':'STRING',
  'println!': "PRINTLN",
  'from':"FROM",
  'char': 'CHAR',
  'u32':'U32',
  'u8':'U8',
  'u16':'U16',
  'u64':'U64',
  'u128':'U128',
  'usize':'USIZE',
  'i8':'I8',
  'i16':'I16',
  'i32': 'I32',
  'i64':'I64',
  'isize':'ISIZE',
  'bool':'BOOL',
  'f32':'F32',
  'f64':'F64',
  #Contribucion Axcel
  'as':'AS',
  'break':'BREAK',
  'const':'CONST',
  'continue':'CONTINUE',
  'crate':'CRATE',
  'enum':'ENUM',
  'loop':'LOOP',
  'mod':'MOD',
  'move':'MOVE',
  'mut':'MUT',
  'pub':'PUB',
  'ref':'REF',
  'return':'RETURN',
  'super':'SUPER',
  'extern':'EXTERN',
  'trait':'TRAIT',
  'type':'TYPE',
  'static':'STATIC',
  'self':'SELFVALUE',
  'unsafe':'UNSAFE',
  'where':'WHERE',
  'use':'USE',
  #Contribución Emilio
  'async': 'ASYNC',
  'await': 'AWAIT',
  'dyn': 'DYN',
  'try': 'TRY',
  'abstract': 'ABSTRACT',
  'become': 'BECOME',
  'box': 'BOX',
  'do': 'DO',
  'final': 'FINAL',
  'macro': 'MACRO',
  'override': 'OVERRIDE',
  'priv': 'PRIV',
  'typeof': 'TYPEOF',
  'unsized': 'UNSIZED',
  'virtual': 'VIRTUAL',
  'yield': 'YIELD',

  'macro_rules': 'MACRO_RULES',
  'union': 'UNION',
  '\'static': '\'STATIC',
}
