reserved = {
  'if': 'IF',
  'else': 'ELSE',
  'while': 'WHILE',
  'for': 'FOR',
  'in': 'IN',
  'fn': 'FN',
  'let': 'LET',
  'true': 'TRUE',
  'false': 'FALSE',
  'and': 'AND',
  'or': 'OR',
  'match':"MATCH",
  'impl':'IMPL',
  'Self':'SELF',
  'str': 'STR',
  'struct':'STRUCT',
  'String':'STRING',
  'println!': "PRINTLN",
  'from':"FROM",
  'char': 'CHAR',
  'mut':'MUT',
  'u32':'U32',
  'u8':'U8',
  'u16':'U16',
  'u64':'U64',
  'u128':'U128',
  'usize':'USIZE',
  'i8':'I8',
  'i16':'I16',
  'i32': 'I32',
  'i64':'I64',
  'isize':'ISIZE',
  'bool':'BOOL',
  'f32':'F32',
  'f64':'F64',
}
